version: "3.7"
services:
  web:
    build: .
    image: my_active_records/ruby:latest
    container_name: my_active_records_web
    tty: true
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - database
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    restart: always
    container_name: my_active_records_db
    volumes:
      - ../.postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
